icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "music"
[[block.click]]
button = "left"
cmd = "ymuse"

[[block]]
block = "weather"
autolocate = true
format = " $icon $weather $temp {$humidity}rh {$wind}mph $direction "
format_alt = " $icon_ffin {$weather_ffin $temp_favg ({$temp_fmin}-{$temp_fmax}) {$humidity_ffin}rh {$wind_ffin}mph $direction_ffin|Unavailable} "
[block.service]
name = "openweathermap"
units = "imperial"

[[block]]
block = "cpu"
interval = 1
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_avail "

[[block]]
block = "amd_gpu"
interval = 1

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"

[[block]]
block = "sound"
device_kind = "sink"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%m/%d %I:%M%p') "
